# Generated by Django 3.0.5 on 2023-03-20 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0002_auto_20230316_0252'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activity',
            table='watch_activity',
        ),
    ]
