# Generated by Django 3.0.5 on 2023-03-20 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0003_auto_20230320_0259'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activity',
            table=None,
        ),
    ]
